# Codex-like System CI/CD Workflow
# This workflow builds and tests the Codex-like system components

name: Codex-like System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Fix docker/distribution version
      run: |
        go get github.com/docker/distribution@v2.7.1
        go mod tidy

    - name: Build API server
      run: go build -v -o bin/api ./cmd/main.go

    - name: Build worker
      run: go build -v ./worker

    - name: Test
      run: go test -v ./internal/... ./utils/...

  agent-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Dockerfiles/agent/go
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Build agent
      run: go build -v .

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-build, agent-build]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build API Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: Dockerfile
        push: false
        tags: codex-api:latest
        load: true

    - name: Build Worker Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/worker/Dockerfile
        push: false
        tags: codex-worker:latest
        load: true

    - name: Build Agent Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/agent/Dockerfile
        push: false
        tags: codex-agent:latest
        load: true
